### ISSUE TITLE
xterm.js 3.0

### ISSUE THREAD

**Issue by parisk** [sourcelair/xterm.js#831]
This is an issue here to keep track of and discuss the candidate upcoming changes in xterm.js 3.0.

Tentative release date is set on the first Monday of November (6 Nov 2017), approx. 3 months after 2.9.0 to give us a fair amount of time to work on the breaking changes and 13 months after 2.0 to justify the new breaking changes 😁.

### 🆕 Candidate features
- [ ] ~~Support for true color (#484 and #756)~~
- [ ] Custom keybindings support (#487)
- [ ] Allow handling of custom escape codes (#576)
- [ ] State serialization, state loading and headless mode (#595, #613)

### ⚠️ Breaking changes ([full list of issues](https://github.com/sourcelair/xterm.js/issues?q=is%3Aissue+label%3Abreaking-change+milestone%3A3.0.0))
- [x] Drop Bower support (#406)
- [x] Stop focusing automatically when opening the terminal in a DOM node (#646)
- [x] Remove attachCustomKeydownHandler in favor of attachCustomKeyEventHandler (#744)

### 🛠 Internal improvements
- [x] Migrate code base to TypeScript (#335)
- [ ] Switch to a CSS preprocessor (from https://github.com/sourcelair/xterm.js/issues/782#issuecomment-315015265)
- [ ] Buffer performance improvements (#791)

### 🎸 Interesting goodies
- [ ] Rebrand the website (https://xtermjs.org) with a dark theme to look more "terminal-y"
- [ ] Introduce an officially supported React component in a separate repo (#260)
- [ ] Incubate the `xterm-terminal` custom element: https://github.com/parisk/xterm-terminal

## Notes
- All issues scheduled for this release should be available at the [3.0.0](https://github.com/sourcelair/xterm.js/milestone/8) milestone.
- All development will happen in the [`v3` release branch](https://github.com/sourcelair/xterm.js/tree/v3).

/cc @Tyriar to make sure you are on track with this.

**Comment by vincentwoo** [comment]
Is there a tentative release date for 2.9.0?

**Comment by parisk** [comment]
@vincentwoo yep. It will be later today.

**Comment by Tyriar** [comment]
My thoughts:

- Add buffer performance improvements https://github.com/sourcelair/xterm.js/issues/791 (this is needed for true color to not blow up the user's memory)
- Remove screen reader (I doubt this will get done)
- Probably remove shell integration as well, I don’t think we should rush into this. I want a solution that will work on all shells/platforms and shell integration only works on macOS/Linux by design.

**Comment by parisk** [comment]
@Tyriar, I added buffer performance improvements and removed the screen reader support.

I kept the custom code handling, as we have a good use case for it in SourceLair. We can continue the discussion in that thread, but the main idea is to implement an API for consumer apps (e.g. SourceLair, VS Code etc.) to handle custom escape codes themselves.

**Comment by Tyriar** [comment]
There are a whole bunch of new changes that have come in, here are the new breaking changes https://github.com/sourcelair/xterm.js/issues?q=is%3Aissue+label%3Abreaking-change+milestone%3A3.0.0

We'll dedicate a section at the top of the release notes for the breaking changes and reasons behind them.

**Comment by parisk** [comment]
👍 I added link to the list of breaking changes issues to the heading of the issue.

**Comment by Tyriar** [comment]
Closing this off as it's pretty out of date at this point, so far the big focuses on v3 have been:

- The new canvas-based renderer and dealing with the fallout from that https://github.com/sourcelair/xterm.js/pull/938
- Making breaking changes that made sense https://github.com/sourcelair/xterm.js/issues?q=is%3Aissue+label%3Abreaking-change+milestone%3A3.0.0

All issues: https://github.com/sourcelair/xterm.js/milestone/8?closed=1
